// Wavelength game prompts (spectrum categories)
export const prompts = [
  { left: "Messy food", right: "Clean food" },
  { left: "Villain", right: "Hero" },
  { left: "Underrated", right: "Overrated" },
  { left: "Guilty pleasure", right: "Publicly acceptable" },
  { left: "Boring", right: "Exciting" },
  { left: "Useless skill", right: "Useful skill" },
  { left: "Bad gift", right: "Great gift" },
  { left: "Luxury item", right: "Necessity" },
  { left: "Terrible movie", right: "Amazing movie" },
  { left: "Weak superpower", right: "Strong superpower" },
  { left: "Easy to learn", right: "Hard to learn" },
  { left: "Bad first date", right: "Great first date" },
  { left: "Winter activity", right: "Summer activity" },
  { left: "Cheap", right: "Expensive" },
  { left: "Hot", right: "Cold" },
  { left: "Safe", right: "Dangerous" },
  { left: "Childish", right: "Mature" },
  { left: "Weak", right: "Strong" },
  { left: "Pointless", right: "Meaningful" },
  { left: "Casual", right: "Formal" },
];
